# Generated by Django 3.0.6 on 2021-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reco', models.BooleanField()),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Medicine', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=50)),
                ('Phno_NO', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('auto_reco', models.BooleanField()),
                ('patient', models.ManyToManyField(to='medical.Patient')),
            ],
        ),
    ]
