# Generated by Django 3.0.6 on 2021-03-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20210302_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='auto_reco',
        ),
    ]
