# Generated by Django 3.0.6 on 2021-03-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_medicine_auto_reco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='auto_reco',
        ),
    ]
